config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home", as: "home"
  resources :ponies, only: [:new, :create, :index, :show, :destroy] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [] do
    member do
      patch :accept
      patch :decline
    end
  end
  get "profile", to: "pages#profile", as: "profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pony

  validates :start_date, :end_date, :user_id, :pony_id, :status, :total_price, presence: true
  validate :start_date_after_time_now
  validate :end_date_after_start_date

  private

  def start_date_after_time_now
    errors.add(:start_date, "You cannot book a poney in the past. Please define a new start date") if start_date.to_date < Date.today
  end

  def end_date_after_start_date
    errors.add(:end_date, "End date must be after start date. Please define a new end date.") if end_date.to_date < start_date.to_date
  end
end

app/models/pony.rb
class Pony < ApplicationRecord
  RACES = ["Shetland", "Welsh", "Connemara", "Chincoteague", "Dartmoor", "Exmoor", "New Forest", "Pony of the Americas", "Icelandic Horse", "Fell"]
  PURPOSES = ["Companionship", "Recreational Riding", "Educational Tool", "Farm work", "Therapeutic Riding", "Competitive Sports", "Conservation Grazing"]
  COAT = %w(
    Bay
    Chestnut/Sorrel
    Black
    Palomino
    Gray
    Buckskin
    Roan
    Appaloosa
    Pinto
    Dun
  )
  SEX = %w(
    Male
    Female
  )

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
  validates :location, :birth_date, :photos, presence: true
  validates :race, presence: true, inclusion: { in: RACES }
  validates :description, presence: true
  validates :coat, presence: true, inclusion: { in: COAT }

  validates :sex, presence: true, inclusion: { in: SEX}

  validates :purpose, presence: true, inclusion: { in: PURPOSES }

  validates :price_per_day, presence: true, numericality: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ponies, dependent: :destroy
  has_many :bookings

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:role, :first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:accept, :decline]
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @pony = Pony.find(params[:pony_id])
    @booking.pony = @pony
    @booking.total_price = @pony.price_per_day * (@booking.end_date.to_date - @booking.start_date.to_date)
    if @booking.save!
      redirect_to profile_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept
    @booking.update(status: "Accepted")
    redirect_to profile_path(current_user), status: :see_other
  end

  def decline
    @booking.update(status: "Declined")
    redirect_to profile_path(current_user), status: :see_other
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def profile
    @user = current_user
    @ponies = @user.ponies
    @bookings_to_validate = Booking.where(pony: @ponies)
  end
end

app/controllers/ponies_controller.rb
class PoniesController < ApplicationController
  before_action :set_pony, only: [:show, :destroy]

  def show
    @booking = Booking.new
    if @pony.geocode
      @marker = [
        lat: @pony.geocode[0],
        lng: @pony.geocode[1]
      ]
    end
  end

  def new
    @pony = Pony.new
  end

  def create
    @pony = Pony.new(pony_params)
    @pony.user = current_user
    if @pony.save!
      redirect_to profile_path(current_user)  # update to pony_path(@pony) when available
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @ponies = Pony.all
    @markers = @ponies.geocoded.map do |pony|
      {
        lat: pony.latitude,
        lng: pony.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { pony: pony })
      }
    end
  end

  def destroy
    @pony.destroy
    redirect_to profile_path(current_user)
  end

  private

  def pony_params
    params.require(:pony).permit(:name, :race, :location, :birth_date, :sex, :purpose, :coat, :description, :price_per_day, photos: [])
  end

  def set_pony
    @pony = Pony.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Paytone+One&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <title>PONYPULSE</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path("pony-pulse.ico") %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>

    <%= render 'shared/navbar' %>

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="home-hero" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path("homepage-hero.jpg") %>">
  <div class="container">
  <div id="half-hero">
      <div class="row">
        <h1 class="h1">Rent beautiful ponies for your events</h1>
      </div>
      <div class="row">
        <p>Live your best life thanks to our ponies : ride, mow or just enjoy the warmth!</p>
      </div>
      <div class="row">
        <%= link_to "Choose your pony", ponies_path(@ponies), class: "btn btn-purple" %>
      </div>
    </div>
  </div>
</div>
<div class="bg-light">
  <div class="container">
  <h2 class="h2 mt-3">Professionnal service</h2>
    <div class="row">
      <div class="col-4 p-3">
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title">🌟 Meet the happiest ponies</h5>
            <p class="card-text">All our ponies live beautiful lives, their owners dedicate themselves to ensuring they have the best environnement to thrive!</p>
          </div>
        </div>
      </div>
      <div class="col-4 p-3">
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title">🐴 The right pony for your moment</h5>
            <p class="card-text">For a memorable birthday, to help during a difficult time or just to lighten the load : we have the right pony for you.</p>
          </div>
        </div>
      </div>
        <div class="col-4 p-3">
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title">💵 Money back guarantee</h5>
            <p class="card-text">Your satisfaction is paramount to us : if for whatever reason you're not satisfied with your pony rental, we'll give you back your money</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="bg-light">
  <div class="container">
    <h2 class="h2">Make great memories</h2>
    <div class="d-flex justify-content-center">
    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="<%= image_path("carousel-home-1.jpeg") %>" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="<%= image_path("carousel-home-2.jpeg") %>" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="<%= image_path("carousel-home-3.jpeg") %>" class="d-block w-100" alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
  </div>
  </div>
  </div>
</div>
<div class="bg-light">
  <div class="container p-3">
  <h2 class="h2">Pony riders & owners love us</h2>
    <div class="card mt-3 mb-3 p-3">
      <h5 class="card-title">⭐️⭐️⭐️⭐️⭐️ I'm a happy father</h5>
      <p class="card-text">My daughter absolultely loved her time with Myrtille, everything went smoothly from the reception to the end. Loved every second of my pony rental, thanks Pony Pulse !</p>
    </div>
    <div class="card mt-3 mb-3 p-3">
      <h5 class="card-title">⭐️⭐️⭐️⭐️⭐️ Jean-Michel loves ponies</h5>
      <p class="card-text">After attending Le Wagon's bootcamp, I really needed to take a break and reconnect with nature. Thanks to Pony Pulse, and especially to Pierre who helped us get set up.</p>
    </div>
    <div class="card mt-3 mb-3 p-3">
      <h5 class="card-title">⭐️⭐️⭐️⭐️⭐️ Finally my pony brings home some cash</h5>
      <p class="card-text">It's been 10 years since I took charge of Max, my shetland pony, and in that time I've spent north of 100k$ just keeping it alive ! With Pony Pulse that lazy bastard cand finally pay some money back.</p>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div id="index-hero" class="cover mb-4 d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path("homepage-hero.jpg") %>">
  <div class="text-center text-white">
    <h1 class="title-white">My profile</h1>
  </div>
</div>

<div class="container">

  <div class="row">
  <h1 class="mt-2 mb-4 title-profile">Manage my ponies</h1>
    <div class="col-6">
      <div class="cards-ponies">
        <h2>My ponies</h2>
        <div class="grid-ponies">
          <% @ponies.each do |pony| %>
              <div class="card-shadow-profile">
                <%= cl_image_tag(pony.photos.first.key, class: "img-rounded", alt: "#{pony.name} Image") %>
                <div class="card-body">
                  <h5 class="card-title mb-2 pt-2"> <b><%= pony.name %></b></h5>
                  <p class="card-text  mb-2"><%= pony.purpose %></p>
                  <p class="card-text"><%= pony.price_per_day %> <i class="fa-solid fa-dollar-sign"></i> per day</p>
                  <%= link_to "Delete", pony_path(pony), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this pony?"}, class:"btn btn-purple"%>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-6">

      <div class="cards-bookings">
        <h2>Bookings to validate</h2>
        <% @bookings_to_validate.each do |booking| %>
          <div class="card-product my-1">
              <%= cl_image_tag(booking.pony.photos.first.key, class: "card-img-top", alt: "#{booking.pony.name} Image") %>
            <div class="card-product-infos">
              <h2>With <%= booking.pony.name%></h2>
              <p>From: <%= booking.start_date %></p>
              <p>To: <%= booking.end_date %></p>
              <p><strong>Amount: <%= booking.total_price %>$</strong></p>
              <% if booking.status == "pending" %>
                <%= link_to "Accept",
                  accept_booking_path(booking),
                  data: {turbo_method: :patch, turbo_confirm: "Are you sure you want to accept this booking ?"},
                  class: "btn btn-purple-booking"
                %>
                <%= link_to "Decline",
                  decline_booking_path(booking),
                  data: {turbo_method: :patch, turbo_confirm: "Are you sure you want to refuse this booking ?"},
                  class: "btn btn-purple-booking"
                %>
              <% elsif booking.status == "Accepted" %>
                <p class="status-confirmed">Confirmation sent</p>
              <% else %>
                <p class="status-declined">Cancelation sent</p>
              <% end %>
            </div>
          </div>
          <% end %>
      </div>

  </div>

  <div class="row">
    <div class="col-6">
       <h1 class="mt-5 mb-4 title-profile">Your future bookings</h1>
      <div class="cards-bookings">
          <h2>Bookings to come  </h2>
          <% @user.bookings.each do |booking| %>
          <div class="card-product my-1">
              <%= cl_image_tag(booking.pony.photos.first.key, class: "card-img-top", alt: "#{booking.pony.name} Image") %>
            <div class="card-product-infos">
              <h2>With <%= booking.pony.name%></h2>
              <p>From: <%= booking.start_date %></p>
              <p>To: <%= booking.end_date %></p>
              <% if booking.status == "Accepted" %>
                <p class="status-confirmed"><%= booking.status %></p>
              <% elsif booking.status == "Declined" %>
                <p class="status-declined"><%= booking.status %></p>
              <% else %>
                <p class="status-pending"><%= booking.status %></p>
              <% end %>
            </div>
          </div>
          <% end %>
      </div>
    </div>

    </div>
  </div>
</div>

app/views/ponies/_info_window.html.erb
<div class="popup-info">
  <h3 class="card-title"><%= pony.name %></h3>
  <p class="card-text">Race:
    <%= pony.race %><br />
    Purpose: <%= pony.purpose %>
  </p>
  <%= link_to 'View', pony_path(pony), class: "btn btn-purple" %>
</div>

app/views/ponies/index.html.erb
<div id="index-hero" class="cover mb-4 d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path("homepage-hero.jpg") %>">
  <div class="text-center text-white">
    <h1 class="title-white">Check out our ponies</h1>
  </div>
</div>

<div class="container">
  <div class="row">
  <h2> <%= @ponies.length %> ponies available </h2>
    <div class="container-cards col-md-8 p-0">
          <% @ponies.each do |pony| %>
            <div class="card-shadow">
              <%= cl_image_tag(pony.photos.first.key, class: "img-rounded", alt: "#{pony.name} Image") %>
              <div class="card-body">
                <h5 class="card-title mb-2 pt-2"> <b><%= pony.name %></b></h5>
                <p class="card-text"><%= pony.purpose %><br/><%= pony.price_per_day %>$</p>
                <%= link_to "More info", pony_path(pony), class: "btn-purple ml-auto mb-2" %>
              </div>
            </div>
          <% end %>

    </div>

    <div class="col-md-4">
      <div class="position-sticky top-0">
        <div class="img-rounded">
        <div style="height: 600px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/ponies/new.html.erb
<div id="index-hero" class="cover mb-4 d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path("homepage-hero.jpg") %>">
  <div class="text-center text-white">
    <h1 class="title-white">Add your pony</h1>
    <h5>Bring joy to riders and showcase your pony's charm by registering you beloved pony</h5>
  </div>
</div>

<div class="container mb-3">
<div class="row justify-content-center">
<div class="col-12 col-lg-6">
  <%= simple_form_for @pony do |f| %>
      <div class="row mb-3">
        <div class="col-md-3">
          <%= f.input :name, label: "🐴 Name" %>
        </div>
        <div class="col-md-3">
          <%= f.input :sex, collection: Pony::SEX, label: "⚤ Sex" %>
        </div>
        <div class="col-md-3">
          <%= f.input :race, collection: Pony::RACES, label: "🧬 Race" %>
        </div>
        <div class="col-md-3">
          <%= f.input :coat, collection: Pony::COAT, label: "🖌️ Coat" %>

        </div>
      </div>

      <!-- Ligne 2 -->
      <div class="row mb-3">
        <div class="col-md-4">
          <%= f.input :birth_date, as: :string, input_html: { data: { controller: "datepicker" } }, label: "🎂 Birthdate" %>
        </div>
        <div class="col-md-4">
          <%= f.input :purpose, collection: Pony::PURPOSES, label: "🎯 Purpose" %>
        </div>
        <div class="col-md-4">
          <%= f.input :price_per_day, label: "💰 Price per day" %>

        </div>
      </div>

      <!-- Ligne 3 -->
      <div class="row mb-3">
        <div class="col-md-6 mw-50">
          <%= f.input :location, input_html: { data: { address_autocomplete_target: "location" }, class: "d-none" }, wrapper_html: { data: { controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"] } }, label: "🗺️ Location" %>
        </div>
        <div class="col-md-6 mw-50">
          <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "📸 Photos" %>
        </div>
      </div>

      <!-- Ligne 4 -->
      <div class="row mb-3">
        <div class="col-md-12">
          <%= f.input :description, label: "✍️ Description", input_html: { placeholder: 'Please describe how nice your pony is' } %>
        </div>
      </div>

      <%= f.button :submit, "Register my pony", class: "btn btn-purple" %>
    <% end %>
</div>
</div>
</div>

app/views/ponies/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-8">
      <div class="">
        <div class="p-3">
          <%= cl_image_tag(@pony.photos.first.key, class: "card-img-top", alt: "#{@pony.name} Image") %>
        </div>
      </div>
    </div>
    <div class="col-4 mt-3">
      <div class="">
      <h1>Meet <%= @pony.name %></h1>
      <p>
          for <%= @pony.purpose %><br />
          only <strong><%= @pony.price_per_day %>$</strong> per day
      </p>
      <%= simple_form_for [@pony, @booking] do |f| %>
        <%= f.input :start_date, as: :string, input_html: { data: { controller: "datepicker" } }  %>
        <%= f.input :end_date, as: :string, input_html: { data: { controller: "datepicker" } }  %>
        <%= f.button :submit, "Book this pony", class: "btn btn-purple" %>
      <% end %>
      </div>
    </div>
  </div>
    <div class="p-3">
      <h2>Description :</h2>
      <p><%= @pony.description %></p>
    </div>
    <div class="p-3">
      <h2>Location :</h2>
      <div style="width: 100%; height: 200px;"
        data-controller="map"
        data-map-markers-value="<%= @marker.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <p><%= @pony.location %></p>
    </div>
          <div class="p-3">
        <h2>Characteristics : </h2>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>Race:</strong> <%= @pony.race %></li>
          <li class="list-group-item"><strong>Coat:</strong> <%= @pony.coat %></li>
          <li class="list-group-item"><strong>Sex:</strong> <%= @pony.sex %></li>
          <li class="list-group-item"><strong>Age:</strong> <%= ((Time.zone.now - @pony.birth_date.to_time) / 1.year.seconds).floor %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
    <div class="footer-container">
      <div class="footer">
        <div class="footer-links mt-3">
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          Pony Pulse © 2023 | In Ponies We Trust | All Right Reserved
        </div>
      </div>
    </div>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid pl-2 mt-3">
      <div class="d-flex align-items-center">
        <%= link_to home_path, class: "navbar-brand d-flex align-items-center" do %>
          <i class="fa-sharp fa-solid fa-horse-head fa-xl" style="color: #7d2ae8"></i>
          <h4 class="title mb-0">PONYPULSE</h4>
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-4">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Discover our ponies", ponies_path(@ponies), class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Add a new pony", new_pony_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "https://avatars.githubusercontent.com/u/147346922?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My profile", profile_path(current_user), class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to "Discover our ponies", ponies_path(@ponies), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link btn-purple" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>